# Generated by Django 5.2.12 on 2026-03-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Unique setting key (e.g., 'site_name')", max_length=100, unique=True)),
                ('value', models.TextField(blank=True, default='', help_text='Setting value')),
                ('setting_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('json', 'JSON'), ('email', 'Email'), ('url', 'URL')], default='text', help_text='Type of value stored', max_length=20)),
                ('category', models.CharField(choices=[('brand', 'Brand'), ('contact', 'Contact'), ('seo', 'SEO'), ('features', 'Features'), ('social', 'Social Media'), ('other', 'Other')], default='other', help_text='Category for grouping settings', max_length=20)),
                ('description', models.TextField(blank=True, default='', help_text='Human-readable description of this setting')),
                ('is_public', models.BooleanField(default=True, help_text='Whether this setting is exposed in the public API')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this setting is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
                'ordering': ['category', 'key'],
                'indexes': [models.Index(fields=['category', 'key'], name='site_settin_categor_12abbd_idx'), models.Index(fields=['key'], name='site_settin_key_97c191_idx')],
            },
        ),
    ]
