# Generated by Django 5.2.12 on 2026-03-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the person submitting the contact form', max_length=200)),
                ('email', models.EmailField(help_text='Email address for response', max_length=254)),
                ('subject', models.CharField(help_text='Subject of the message', max_length=300)),
                ('message', models.TextField(help_text='Message content')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('spam', 'Spam')], default='new', help_text='Current status of the submission', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of submitter', null=True)),
                ('user_agent', models.TextField(blank=True, default='', help_text='Browser/user agent information')),
                ('notes', models.TextField(blank=True, default='', help_text='Internal admin notes for follow-up')),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='contact_con_status_0384dd_idx'), models.Index(fields=['email', '-created_at'], name='contact_con_email_5fca2d_idx')],
            },
        ),
    ]
