# Generated by Django 5.2.12 on 2026-03-11 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_alter_tool_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly category name', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Category description')),
                ('icon', models.CharField(blank=True, default='', help_text="Icon class name (e.g., 'fa fa-pdf')", max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the category was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the category was last updated')),
            ],
            options={
                'verbose_name': 'Tool Category',
                'verbose_name_plural': 'Tool Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Tool', 'verbose_name_plural': 'Tools'},
        ),
        migrations.AddField(
            model_name='tool',
            name='icon',
            field=models.ImageField(blank=True, help_text='Tool icon', null=True, upload_to='tools/icons/'),
        ),
        migrations.AddField(
            model_name='tool',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the tool is active'),
        ),
        migrations.AddField(
            model_name='tool',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional tool metadata'),
        ),
        migrations.AddField(
            model_name='tool',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order'),
        ),
        migrations.AddField(
            model_name='tool',
            name='short_description',
            field=models.CharField(blank=True, default='', help_text='Short description for previews', max_length=300),
        ),
        migrations.AddField(
            model_name='tool',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly tool name', max_length=220, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the tool was last updated'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='category',
            field=models.CharField(blank=True, default='', help_text='Legacy category (for backward compatibility)', max_length=100),
        ),
        migrations.AlterField(
            model_name='tool',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the tool was created'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=models.TextField(help_text='Tool description'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(help_text='Tool name', max_length=200),
        ),
        migrations.AlterField(
            model_name='tool',
            name='website',
            field=models.URLField(help_text='Tool website URL'),
        ),
        migrations.AddField(
            model_name='tool',
            name='tool_category',
            field=models.ForeignKey(blank=True, help_text='Category (new relation)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='tools.toolcategory'),
        ),
    ]
