# Generated by Django 5.2.12 on 2026-03-11 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Category name', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly category name', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Category description')),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code for display', max_length=7)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Tag name', max_length=50, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly tag name', max_length=55, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Post title', max_length=300)),
                ('slug', models.SlugField(help_text='URL-friendly post title', max_length=320, unique=True)),
                ('excerpt', models.TextField(help_text='Short summary for previews', max_length=500)),
                ('content', models.TextField(help_text='Full post content')),
                ('featured_image', models.ImageField(blank=True, help_text='Featured image URL', null=True, upload_to='blog/featured/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Post status', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, help_text='When the post was published', null=True)),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of views')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this post on the homepage')),
                ('author', models.ForeignKey(blank=True, help_text='Post author', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, help_text='Post category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogcategory')),
                ('tags', models.ManyToManyField(blank=True, help_text='Post tags', related_name='posts', to='blog.tag')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['status', '-published_at'], name='blog_blogpo_status_c0e87f_idx'), models.Index(fields=['category', '-published_at'], name='blog_blogpo_categor_dbd54f_idx')],
            },
        ),
    ]
