# Generated by Django 5.2.12 on 2026-03-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='seo',
            field=models.JSONField(blank=True, default=dict, help_text="SEO metadata: {'metaTitle': str, 'metaDescription': str}"),
        ),
    ]
