# Generated by Django 5.2.12 on 2026-03-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(help_text="Subscriber's email address", max_length=254, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('unsubscribed', 'Unsubscribed'), ('bounced', 'Bounced')], default='active', help_text='Subscription status', max_length=20)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, help_text='When the user subscribed')),
                ('unsubscribed_at', models.DateTimeField(blank=True, help_text='When the user unsubscribed (if applicable)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address at time of subscription', null=True)),
                ('confirmation_token', models.CharField(blank=True, help_text='Token for email confirmation', max_length=64, null=True, unique=True)),
                ('is_confirmed', models.BooleanField(default=False, help_text='Whether the email has been confirmed')),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
                'ordering': ['-subscribed_at'],
                'indexes': [models.Index(fields=['status', '-subscribed_at'], name='newsletter__status_525dba_idx')],
            },
        ),
    ]
