"""
Django settings for skycodetools project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
# This allows storing sensitive configuration outside the codebase
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Use environment variable in production, fallback to a strong key for development
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-8d-j0h%dqb03p*+34c3g_b2sg$yub*8jo&ia2suyk&+2kw(%pr')

# SECURITY WARNING: don't run with debug turned on in production!
# Use environment variable to control DEBUG mode
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('true', '1', 'yes')

# ALLOWED_HOSTS configuration
# For development: localhost and 127.0.0.1
# For production: configure via ALLOWED_HOSTS environment variable (comma-separated)
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS if host.strip()]


# Application definition

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
# ]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'corsheaders',
    'tools',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'skycodetools.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'skycodetools.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'skycodetoolsdb',
        'USER': 'postgres',
        'PASSWORD': 'AkashyRakhi7678@',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# STATIC_ROOT: The directory where Django will collect static files for deployment
# Run: python manage.py collectstatic
STATIC_ROOT = BASE_DIR / 'staticfiles'

# STATICFILES_DIRS: Additional directories where Django looks for static files
# Use this for project-level static files (not in apps)
# Example: STATICFILES_DIRS = [BASE_DIR / 'static',]
STATICFILES_DIRS = []

CORS_ALLOW_ALL_ORIGINS = True


# =============================================================================
# API Keys Configuration
# =============================================================================
# Load API keys from environment variables for security
# Never hardcode API keys in the codebase

# remove.bg API key for background removal feature
# Get from: https://www.remove.bg/api
REMOVE_BG_API_KEY = os.getenv('REMOVE_BG_API_KEY', '').strip()


# =============================================================================
# PRODUCTION SECURITY SETTINGS (enabled only when DEBUG=False)
# =============================================================================
# These settings are applied conditionally based on the DEBUG setting

if not DEBUG:
    # -----------------------------------------------------------------------------
    # SSL/HTTPS Settings
    # -----------------------------------------------------------------------------
    # Redirect all HTTP requests to HTTPS
    SECURE_SSL_REDIRECT = True
    
    # HTTP Strict Transport Security - enforce HTTPS for 1 year (31536000 seconds)
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Tell browsers to only use HTTPS for future requests
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # -----------------------------------------------------------------------------
    # Cookie Security Settings
    # -----------------------------------------------------------------------------
    # Ensure session cookies are only sent over HTTPS
    SESSION_COOKIE_SECURE = True
    
    # Ensure CSRF cookies are only sent over HTTPS
    CSRF_COOKIE_SECURE = True
    
    # -----------------------------------------------------------------------------
    # Additional Security Headers
    # -----------------------------------------------------------------------------
    # Prevent content type sniffing
    SECURE_CONTENT_TYPE_NOSNIFF = True
    
    # Enable browser XSS filtering
    SECURE_BROWSER_XSS_FILTER = True
    
    # Require HTTPS for cookie transmission (if not using SESSION_COOKIE_SECURE)
    # CSRF_COOKIE_HTTPONLY = True  # Optional: if you don't need JS access to CSRF token

# -----------------------------------------------------------------------------
# Development vs Production Settings Summary
# -----------------------------------------------------------------------------
# 
# LOCAL DEVELOPMENT (DEBUG=True):
#   - DEBUG: True (shows detailed error pages)
#   - ALLOWED_HOSTS: localhost, 127.0.0.1
#   - SECRET_KEY: Weak default key (OK for dev only)
#   - SECURE_SSL_REDIRECT: False
#   - SECURE_HSTS_SECONDS: 0 (not enforced)
#   - SESSION_COOKIE_SECURE: False
#   - CSRF_COOKIE_SECURE: False
#   - SECURE_CONTENT_TYPE_NOSNIFF: False
#   - SECURE_BROWSER_XSS_FILTER: False
#
# PRODUCTION (DEBUG=False):
#   - DEBUG: False (shows generic error pages)
#   - ALLOWED_HOSTS: Configure via ALLOWED_HOSTS env var
#   - SECRET_KEY: MUST set via DJANGO_SECRET_KEY env var
#   - SECURE_SSL_REDIRECT: True (redirects HTTP to HTTPS)
#   - SECURE_HSTS_SECONDS: 31536000 (1 year)
#   - SECURE_HSTS_INCLUDE_SUBDOMAINS: True
#   - SECURE_HSTS_PRELOAD: True
#   - SESSION_COOKIE_SECURE: True
#   - CSRF_COOKIE_SECURE: True
#   - SECURE_CONTENT_TYPE_NOSNIFF: True
#   - SECURE_BROWSER_XSS_FILTER: True
#
# -----------------------------------------------------------------------------
# Environment Variables for Production
# -----------------------------------------------------------------------------
# Required for production deployment:
#   export DEBUG=False
#   export DJANGO_SECRET_KEY=<your-strong-random-secret-key>
#   export ALLOWED_HOSTS=yourdomain.com,www.yourdomain.com
#   export DATABASE_URL=postgres://user:password@host:port/dbname
# 
