# Generated by Django 5.2.12 on 2026-03-11 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0003_toolcategory_alter_tool_options_tool_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback_type', models.CharField(choices=[('bug', 'Bug Report'), ('feature', 'Feature Request'), ('improvement', 'Improvement'), ('other', 'Other')], default='other', help_text='Type of feedback', max_length=20)),
                ('title', models.CharField(help_text='Brief title/summary of the feedback', max_length=300)),
                ('description', models.TextField(help_text='Detailed description')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('planned', 'Planned'), ('implemented', 'Implemented'), ('rejected', 'Rejected'), ('spam', 'Spam')], default='new', help_text='Current status of the feedback', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of submitter', null=True)),
                ('attachments', models.FileField(blank=True, help_text='Screenshots or files related to the feedback', null=True, upload_to='feedback/attachments/')),
                ('tool', models.ForeignKey(blank=True, help_text='Related tool (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='tools.tool')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='feedback_fe_status_212662_idx'), models.Index(fields=['feedback_type', '-created_at'], name='feedback_fe_feedbac_6b63a4_idx')],
            },
        ),
    ]
